version: '3.0'
services:
  web:
    container_name: web_php
    build: .
    ports:
      - '2000:80'
    volumes:
      - ./html/:/var/www/html/
    links:
      - db
  db:
    container_name: db
    image: mariadb
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=r00t
      - MYSQL_DATABASE=db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    volumes:
      - ./database:/var/lib/mysql
    command: --lower_case_table_names=1 --character-set-server=utf8 --collation-server=utf8_general_ci
